# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 19:57
from __future__ import unicode_literals

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20170414_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='richtext',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='post',
            name='richtextuploads',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
