# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 20:05
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_remove_post_richtextuploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='richtextuploads',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
